<a href="https://colab.research.google.com/github/harsha-9977/AIML/blob/main/DataFrameSorting%26MultiIndex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# df.sort_values(by='bloodtype')
# df.sort_values(by='bloodtype', ascending=False)
# df.sort_values(by=['bloodtype','gender'])

In [1]:
import numpy as np
import pandas as pd

In [4]:
my_header = ['a','b','c']
my_index_out = ['G1']*3 + ['G2']*3
my_index_in = [1,2,3]*2
my_index_zipped = list(zip(my_index_out, my_index_in))
my_index = pd.MultiIndex.from_tuples(my_index_zipped)
df = pd.DataFrame(data = np.random.randn(6,3), index=my_index, columns=my_header)
df

             a         b         c
G1 1 -1.265918 -0.892456 -1.204861
   2 -1.204224  0.484268 -0.143278
   3 -1.352103 -0.186446 -1.611678
G2 1  0.995363  0.710138  0.845134
   2  0.749207 -1.482339 -0.190370
   3 -1.109631  2.038544  0.228712

In [5]:
import os
import pandas as pd

In [6]:
!wget --no-clobber https://raw.githubusercontent.com/stefannae/SIC-Artificial-Intelligence/main/SIC_AI_Coding_Exercises/SIC_AI_Chapter_04_Coding_Exercises/data_studentlist.csv

--2025-07-21 18:11:54--  https://raw.githubusercontent.com/stefannae/SIC-Artificial-Intelligence/main/SIC_AI_Coding_Exercises/SIC_AI_Chapter_04_Coding_Exercises/data_studentlist.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 674 [text/plain]
Saving to: ‘data_studentlist.csv’

data_studentlist.cs 100%[===================>]     674  --.-KB/s    in 0s

2025-07-21 18:11:54 (30.8 MB/s) - ‘data_studentlist.csv’ saved [674/674]

In [7]:
df = pd.read_csv('data_studentlist.csv')
df

                name gender  age  grade absence bloodtype  height  weight
0      Jared Diamond      M   23      3       Y         O   165.3    68.2
1     Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2       Brian Martin      M   24      4       N         B   175.0    80.1
3       David Hassel      M   23      3       N        AB   182.1    85.7
4    Clara Rodriquez      F   20      1       Y         A   168.0    49.5
5   Jennifer Lorentz      F   21      2       N         O   162.0    52.0
6        Susan Clark      F   22      1       N         O   155.2    45.3
7    Margareth Jones      F   23      1       N         A   176.9    55.0
8       John Bertsch      M   23      3       N         B   178.5    64.2
9     Jake Timmerman      M   22      2       N         B   176.1    61.3
10     Joshua Connor      M   24      4       Y         O   167.1    62.0
11      John Matsuda      M   22      2       N        AB   180.0    75.8
12      Eddy Johnson      M   21      1       N         A   162.2    55.3
13  Rebecah Anderson      F   23      3       N         O   176.1    53.1
14      Linda Carter      F   22      2       N         B   158.2    45.2
15    Richard Swayze      M   24      4       Y         B   168.6    70.2
16       Andrew King      M   21      1       N         A   169.2    62.2

In [8]:
df.groupby(['gender','bloodtype'])['height'].mean()

gender  bloodtype
F       A            172.450000
        AB           170.100000
        B            158.200000
        O            164.433333
M       A            165.700000
        AB           181.050000
        B            174.550000
        O            166.200000
Name: height, dtype: float64

In [9]:
my_dict = {
    'Size' : ['L','L','M','M','M','S','S','S','S'],
    'Type' : ['A','A','A','B','B','A','A','B','B'],
    'Location' : ['L1','L1','L1','L2','L2','L1','L2','L2','L1'],
    'A' : [1,2,2,3,3,4,5,6,7],
    'B' : [2,4,5,5,6,6,8,9,9]
}
df = pd.DataFrame(my_dict)
df

  Size Type Location  A  B
0    L    A       L1  1  2
1    L    A       L1  2  4
2    M    A       L1  2  5
3    M    B       L2  3  5
4    M    B       L2  3  6
5    S    A       L1  4  6
6    S    A       L2  5  8
7    S    B       L2  6  9
8    S    B       L1  7  9

In [10]:
dfr = pd.pivot_table(df, index=['Size','Type'], columns='Location', values='B')
dfr

Location    L1   L2
Size Type
L    A     3.0  NaN
M    A     5.0  NaN
     B     NaN  5.5
S    A     6.0  8.0
     B     9.0  9.0

In [11]:
dfr.columns

Index(['L1', 'L2'], dtype='object', name='Location')

In [12]:
dfr.index

MultiIndex([('L', 'A'),
            ('M', 'A'),
            ('M', 'B'),
            ('S', 'A'),
            ('S', 'B')],
           names=['Size', 'Type'])

In [13]:
pd.pivot_table(df, index=['Size','Type'], columns='Location', values='B', fill_value=0)

Location    L1   L2
Size Type
L    A     3.0  0.0
M    A     5.0  0.0
     B     0.0  5.5
S    A     6.0  8.0
     B     9.0  9.0

In [14]:
import numpy as np

In [15]:
pd.pivot_table(df, index=['Size','Type'], columns='Location', values='B', aggfunc = np.mean, fill_value=0)

/tmp/ipython-input-15-2902245159.py:1: FutureWarning: The provided callable <function mean at 0x7bb89dd26200> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(df, index=['Size','Type'], columns='Location', values='B', aggfunc = np.mean, fill_value=0)

Location    L1   L2
Size Type
L    A     3.0  0.0
M    A     5.0  0.0
     B     0.0  5.5
S    A     6.0  8.0
     B     9.0  9.0

In [16]:
dfr = pd.pivot_table(df,index='Location', columns=['Size','Type'], values='B')
dfr

Size        L    M         S
Type        A    A    B    A    B
Location
L1        3.0  5.0  NaN  6.0  9.0
L2        NaN  NaN  5.5  8.0  9.0

In [17]:
dfr.index

Index(['L1', 'L2'], dtype='object', name='Location')

In [18]:
dfr.columns

MultiIndex([('L', 'A'),
            ('M', 'A'),
            ('M', 'B'),
            ('S', 'A'),
            ('S', 'B')],
           names=['Size', 'Type'])

In [20]:
pd.pivot_table(df, index=['Size','Type'], columns='Location', values='B', aggfunc=np.median, fill_value=0)

/tmp/ipython-input-20-1697354663.py:1: FutureWarning: The provided callable <function median at 0x7bb89dc8b880> is currently using DataFrameGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  pd.pivot_table(df, index=['Size','Type'], columns='Location', values='B', aggfunc=np.median, fill_value=0)

Location    L1   L2
Size Type
L    A     3.0  0.0
M    A     5.0  0.0
     B     0.0  5.5
S    A     6.0  8.0
     B     9.0  9.0

In [21]:
pd.pivot_table(df, index=['Size','Type'], values=['A','B'], aggfunc=np.mean)

/tmp/ipython-input-21-2269344164.py:1: FutureWarning: The provided callable <function mean at 0x7bb89dd26200> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(df, index=['Size','Type'], values=['A','B'], aggfunc=np.mean)

             A    B
Size Type
L    A     1.5  3.0
M    A     2.0  5.0
     B     3.0  5.5
S    A     4.5  7.0
     B     6.5  9.0

In [22]:
df.groupby(['Size','Type'])[['A','B']].mean()

             A    B
Size Type
L    A     1.5  3.0
M    A     2.0  5.0
     B     3.0  5.5
S    A     4.5  7.0
     B     6.5  9.0

In [23]:
pd.pivot_table(df, index=['Size','Type'], values=['A','B'], aggfunc={'A':np.max, 'B':np.min})

/tmp/ipython-input-23-978555670.py:1: FutureWarning: The provided callable <function max at 0x7bb89dd25800> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  pd.pivot_table(df, index=['Size','Type'], values=['A','B'], aggfunc={'A':np.max, 'B':np.min})
/tmp/ipython-input-23-978555670.py:1: FutureWarning: The provided callable <function min at 0x7bb89dd25940> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  pd.pivot_table(df, index=['Size','Type'], values=['A','B'], aggfunc={'A':np.max, 'B':np.min})

           A  B
Size Type
L    A     2  2
M    A     2  5
     B     3  5
S    A     5  6
     B     7  9

In [24]:
df.sum(axis=0)

Size                 LLMMMSSSS
Type                 AAABBAABB
Location    L1L1L1L2L2L1L2L2L1
A                           33
B                           54
dtype: object

In [26]:
df.sum(axis=1)

TypeError: can only concatenate str (not "int") to str

In [27]:
df.mean(axis=0, skipna=False)

TypeError: Could not convert ['LLMMMSSSS' 'AAABBAABB' 'L1L1L1L2L2L1L2L2L1'] to numeric

In [28]:
df.describe()

              A         B
count  9.000000  9.000000
mean   3.666667  6.000000
std    2.000000  2.345208
min    1.000000  2.000000
25%    2.000000  5.000000
50%    3.000000  6.000000
75%    5.000000  8.000000
max    7.000000  9.000000

In [29]:
df.count(axis=0)

Size        9
Type        9
Location    9
A           9
B           9
dtype: int64

In [30]:
df.A.corr(df.B)

np.float64(0.9594032236002469)

In [31]:
df.corr()

ValueError: could not convert string to float: 'L'

In [32]:
df.corrwith(df.A)

ValueError: could not convert string to float: 'L'

In [33]:
df.isnull()

    Size   Type  Location      A      B
0  False  False     False  False  False
1  False  False     False  False  False
2  False  False     False  False  False
3  False  False     False  False  False
4  False  False     False  False  False
5  False  False     False  False  False
6  False  False     False  False  False
7  False  False     False  False  False
8  False  False     False  False  False

In [34]:
(df.isnull()).sum(axis=0)

Size        0
Type        0
Location    0
A           0
B           0
dtype: int64

In [35]:
(df.isnull()).mean(axis=0)

Size        0.0
Type        0.0
Location    0.0
A           0.0
B           0.0
dtype: float64

In [36]:
df.dropna(axis=0)

  Size Type Location  A  B
0    L    A       L1  1  2
1    L    A       L1  2  4
2    M    A       L1  2  5
3    M    B       L2  3  5
4    M    B       L2  3  6
5    S    A       L1  4  6
6    S    A       L2  5  8
7    S    B       L2  6  9
8    S    B       L1  7  9

In [37]:
df.dropna(axis=1)

  Size Type Location  A  B
0    L    A       L1  1  2
1    L    A       L1  2  4
2    M    A       L1  2  5
3    M    B       L2  3  5
4    M    B       L2  3  6
5    S    A       L1  4  6
6    S    A       L2  5  8
7    S    B       L2  6  9
8    S    B       L1  7  9

In [38]:
df.dropna(axis=0,thresh=3)

  Size Type Location  A  B
0    L    A       L1  1  2
1    L    A       L1  2  4
2    M    A       L1  2  5
3    M    B       L2  3  5
4    M    B       L2  3  6
5    S    A       L1  4  6
6    S    A       L2  5  8
7    S    B       L2  6  9
8    S    B       L1  7  9

In [39]:
df.fillna(value=0)

  Size Type Location  A  B
0    L    A       L1  1  2
1    L    A       L1  2  4
2    M    A       L1  2  5
3    M    B       L2  3  5
4    M    B       L2  3  6
5    S    A       L1  4  6
6    S    A       L2  5  8
7    S    B       L2  6  9
8    S    B       L1  7  9