<a href="https://colab.research.google.com/github/harsha-9977/AIML/blob/main/Merging%26BindingDataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd

In [10]:
df_left = {
    'Name' : ['Harry Potter', 'David Baker', 'John Smith', 'Jaun Martinez', 'Jane Conner'],
    'Gender' : ['Male','Male','Male','Male','Female'],
    'Age' : [23,31,22,36,30]
}

In [11]:
df_left = pd.DataFrame(df_left)
df_left

            Name  Gender  Age
0   Harry Potter    Male   23
1    David Baker    Male   31
2     John Smith    Male   22
3  Jaun Martinez    Male   36
4    Jane Conner  Female   30

In [12]:
df_right = {
    'Name' : ['John Smith', 'Alex Du Bois', 'Joanne Rowling', 'Jane Conner'],
    'Position' : ['Intern', 'Team Lead', 'Manager', 'Manager'],
    'Wage' : [25000, 75000, 90000, 70000]
}

In [13]:
df_right = pd.DataFrame(df_right)
df_right

             Name   Position   Wage
0      John Smith     Intern  25000
1    Alex Du Bois  Team Lead  75000
2  Joanne Rowling    Manager  90000
3     Jane Conner    Manager  70000

In [14]:
# Inner Join!
pd.merge(df_left, df_right, on='Name')

          Name  Gender  Age Position   Wage
0   John Smith    Male   22   Intern  25000
1  Jane Conner  Female   30  Manager  70000

In [19]:
# Inner Join!
pd.merge(df_left, df_right, left_on='Name', right_on='Name', how='inner')

          Name  Gender  Age Position   Wage
0   John Smith    Male   22   Intern  25000
1  Jane Conner  Female   30  Manager  70000

In [20]:
# Left Join!
pd.merge(df_left, df_right, left_on='Name', right_on='Name', how='left')

            Name  Gender  Age Position     Wage
0   Harry Potter    Male   23      NaN      NaN
1    David Baker    Male   31      NaN      NaN
2     John Smith    Male   22   Intern  25000.0
3  Jaun Martinez    Male   36      NaN      NaN
4    Jane Conner  Female   30  Manager  70000.0

In [21]:
# Right Join!
pd.merge(df_left, df_right, left_on='Name', right_on='Name', how='right')

             Name  Gender   Age   Position   Wage
0      John Smith    Male  22.0     Intern  25000
1    Alex Du Bois     NaN   NaN  Team Lead  75000
2  Joanne Rowling     NaN   NaN    Manager  90000
3     Jane Conner  Female  30.0    Manager  70000

In [22]:
# Outer Join!
pd.merge(df_left, df_right, left_on='Name', right_on='Name', how='outer')

             Name  Gender   Age   Position     Wage
0    Alex Du Bois     NaN   NaN  Team Lead  75000.0
1     David Baker    Male  31.0        NaN      NaN
2    Harry Potter    Male  23.0        NaN      NaN
3     Jane Conner  Female  30.0    Manager  70000.0
4   Jaun Martinez    Male  36.0        NaN      NaN
5  Joanne Rowling     NaN   NaN    Manager  90000.0
6      John Smith    Male  22.0     Intern  25000.0

In [23]:
pd.concat([df_left, df_right], sort=True)

    Age  Gender            Name   Position     Wage
0  23.0    Male    Harry Potter        NaN      NaN
1  31.0    Male     David Baker        NaN      NaN
2  22.0    Male      John Smith        NaN      NaN
3  36.0    Male   Jaun Martinez        NaN      NaN
4  30.0  Female     Jane Conner        NaN      NaN
0   NaN     NaN      John Smith     Intern  25000.0
1   NaN     NaN    Alex Du Bois  Team Lead  75000.0
2   NaN     NaN  Joanne Rowling    Manager  90000.0
3   NaN     NaN     Jane Conner    Manager  70000.0

In [24]:
pd.concat([df_left, df_right], axis=1, sort=True)

            Name  Gender  Age            Name   Position     Wage
0   Harry Potter    Male   23      John Smith     Intern  25000.0
1    David Baker    Male   31    Alex Du Bois  Team Lead  75000.0
2     John Smith    Male   22  Joanne Rowling    Manager  90000.0
3  Jaun Martinez    Male   36     Jane Conner    Manager  70000.0
4    Jane Conner  Female   30             NaN        NaN      NaN

In [25]:
import pandas as pd

In [27]:
df1 = pd.DataFrame({
    'a' : ['a0','a1','a2','a3'],
    'b' : ['b0','b1','b2','b3'],
    'c' : ['c0','c1','c2','c3']},
    index = [0,1,2,3])
df1

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3

In [28]:
df2 = pd.DataFrame({
    'a' : ['a2','a3','a4','a5'],
    'b' : ['b2','b3','b4','b5'],
    'c' : ['c2','c3','c4','c5'],
    'd' : ['d2','d3','d4','d5']},
    index = [2,3,4,5])
df2

    a   b   c   d
2  a2  b2  c2  d2
3  a3  b3  c3  d3
4  a4  b4  c4  d4
5  a5  b5  c5  d5

In [29]:
pd.concat([df1,df2])

    a   b   c    d
0  a0  b0  c0  NaN
1  a1  b1  c1  NaN
2  a2  b2  c2  NaN
3  a3  b3  c3  NaN
2  a2  b2  c2   d2
3  a3  b3  c3   d3
4  a4  b4  c4   d4
5  a5  b5  c5   d5

In [30]:
pd.concat([df1,df2], ignore_index=True)

    a   b   c    d
0  a0  b0  c0  NaN
1  a1  b1  c1  NaN
2  a2  b2  c2  NaN
3  a3  b3  c3  NaN
4  a2  b2  c2   d2
5  a3  b3  c3   d3
6  a4  b4  c4   d4
7  a5  b5  c5   d5

In [31]:
pd.concat([df1,df2], axis=1)

     a    b    c    a    b    c    d
0   a0   b0   c0  NaN  NaN  NaN  NaN
1   a1   b1   c1  NaN  NaN  NaN  NaN
2   a2   b2   c2   a2   b2   c2   d2
3   a3   b3   c3   a3   b3   c3   d3
4  NaN  NaN  NaN   a4   b4   c4   d4
5  NaN  NaN  NaN   a5   b5   c5   d5